### ISSUE TITLE
Replace Translation

### ISSUE THREAD

**Issue by xenonca** [LoneWolfHT/lavastuff#5]
https://github.com/LoneWolfHT/lavastuff/blob/6d8d2f2c92d00da4142d48521176b2ff59cb6935/locale/lavastuff.es.tr#L10

Use `Pantalones` instead of ~~`Polainas`~~

**Comment by xenonca** [comment]
https://github.com/LoneWolfHT/lavastuff/blob/6d8d2f2c92d00da4142d48521176b2ff59cb6935/locale/lavastuff.fr.tr#L11

Botte**s**

**Comment by LoneWolfHT** [comment]
Fixed, thanks!
