### ISSUE TITLE
right-clicking on doors and similar nodes should not place fire

### ISSUE THREAD

**Issue by SwissalpS** [LoneWolfHT/lavastuff#6]
Doors, anvil, item frames, item holders etc. should not burst into flame in my opinion.
Also any node that has a formspec should show the formspec and not burst into flame.

**Comment by LoneWolfHT** [comment]
Hmmmm, I guess you have a point. I'll look into adding a flammability check

**Comment by SwissalpS** [comment]
on pandorabox.io technic seems to work.

**Comment by LoneWolfHT** [comment]
Should be fixed now. Make sure fire isn't enabled on the server though. Or you'll set your door on fire \:P

**Comment by SwissalpS** [comment]
It wasn't fixed. [This PR should fix it though.](https://github.com/minetest-mods/lavastuff/pull/8)
@LoneWolfHT
